// spots_data.js - 預設景點與車站資料庫 (解析自 新文字文件.txt)
const DEFAULT_SPOTS = [
  {
  "id": "okayama_hotel",
  "name": "岡山站前飯店 (住宿 Check-in)",
  "prefecture": "岡山",
  "type": "lodging",
  "lat": 34.6655,
  "lng": 133.9185,
  "stayDuration": "夜宿",
  "climbLevel": "lodging",
  "climbLevelText": "🏨 站前市區住宿 (Check-in 寄放行李)",
  "nearestStation": "岡山駅",
  "stampLocation": "",
  "closedDay": "None",
  "closedDayText": "全年無休",
  "backupStamp": "",
  "openHours": "15:00 Check-in",
  "transitInfo": "岡山桃太郎機場搭乘利木津巴士約 30 分直達岡山站西口 (徒步 1~3 分進飯店)",
  "reservationUrl": "",
  "notes": "岡山站直結或站前精選飯店（如 Hotel Granvia Okayama / Daiwa Roynet / Mitsui Garden），交通樞紐核心，放下大件行李後即可輕鬆空手出門逛街與享用和牛。"
},
  {
  "id": "okayama_aeon",
  "name": "AEON Mall Okayama (西日本最大級・逛街採買)",
  "prefecture": "岡山",
  "type": "custom",
  "lat": 34.6628,
  "lng": 133.9189,
  "stayDuration": "1.5 ~ 2 小時",
  "climbLevel": "shopping",
  "climbLevelText": "🛍️ 大型購物商場 (室內平坦好走)",
  "nearestStation": "岡山駅",
  "stampLocation": "",
  "closedDay": "None",
  "closedDayText": "無休",
  "backupStamp": "",
  "openHours": "10:00 - 21:00",
  "transitInfo": "JR 岡山站地下街直結，徒步約 5 分鐘即達",
  "reservationUrl": "https://aeonmall-okayama.com/",
  "notes": "西日本最大規模都市型 AEON，地下 2 層地上 8 層，進駐 350 家店鋪，涵蓋大規模超市、Bic Camera 電器、各類日系服飾、生活雜貨與免稅店，補給旅行物資首選。"
},
  {
    "id": "kinojo",
    "name": "鬼ノ城",
    "prefecture": "岡山",
    "type": "castle",
    "lat": 34.7297,
    "lng": 133.7661,
    "stayDuration": "1.5 ~ 2 小時",
    "climbLevel": "mountain_mid",
    "climbLevelText": "⛰️ 古代山城（步道巡禮需爬坡，建議預留 1.5~2h）",
    "nearestStation": "総社駅",
    "stampLocation": "鬼城山ビジターセンター (9:00～17:00)",
    "closedDay": "Monday",
    "closedDayText": "週一休息 (休館時至「総社市埋蔵文化財学習の館」蓋章 9:00～16:00)",
    "backupStamp": "総社市埋蔵文化財学習の館 (9:00～16:00)",
    "openHours": "09:00 - 17:00",
    "transitInfo": "吉備線・伯備線「総社駅」からタクシー約30分 (山頂無定期公車，建議回程預約)",
    "reservationUrl": "",
    "notes": "名城編號 69。山頂俯瞰吉備平野視野極佳。下計程車後需步行陡坡前往西門與城郭巡禮，建議預留 1.5 ~ 2 小時；下車時請務必先與司機約定下山回程時間。"
  },
  {
    "id": "bitchu_matsuyama",
    "name": "備中松山城",
    "prefecture": "岡山",
    "type": "castle",
    "lat": 34.7958,
    "lng": 133.6225,
    "stayDuration": "1.5 ~ 2 小時",
    "climbLevel": "mountain_hard",
    "climbLevelText": "⛰️ 現存唯一高山天守（鞴峠接駁＋攀爬20分石階山道，建議預留 1.5~2h）",
    "nearestStation": "備中高梁駅",
    "stampLocation": "備中松山城券売所 (9:00～16:30)",
    "closedDay": "None",
    "closedDayText": "無休 (年末年始除外)",
    "backupStamp": "",
    "openHours": "09:00 - 16:30",
    "transitInfo": "伯備線「備中高梁駅」前観光案内所より『観光乗合タクシー』を運行 (約15分至鞴峠/ふいご峠，再步行20分攻頂)",
    "reservationUrl": "https://www.asoview.com/item/activity/pln3000045984/",
    "notes": "名城編號 68。現存十二天守唯一山城、標高430m、貓城主「三十郎」。乘合計程車抵達鞴峠後，需步行攀登 20 分鐘石階陡坡攻頂，天守參觀＋往返步道建議預留 1.5 ~ 2 小時。務必提前預約乘合計程車！"
  },
  {
    "id": "tsuyama",
    "name": "津山城",
    "prefecture": "岡山",
    "type": "castle",
    "lat": 35.0645,
    "lng": 134.0048,
    "stayDuration": "1 小時",
    "climbLevel": "flat",
    "climbLevelText": "平山城（鶴山公園平緩好走，基本預留 1h）",
    "nearestStation": "津山駅",
    "stampLocation": "津山城備中櫓受付 (8:40～17:00)",
    "closedDay": "None",
    "closedDayText": "無休 (12/29-12/31休)",
    "backupStamp": "",
    "openHours": "08:40 - 17:00",
    "transitInfo": "JR 姫新線・津山線「津山駅」徒步10分，或搭「ごんごバス」左迴線至「観光センター前」下車",
    "reservationUrl": "",
    "notes": "名城編號 67。鶴山公園，西日本著名賞櫻百選名所，高大石垣與備中櫓極為壯觀。園區平緩好走，基本預留 1 小時。"
  },
  {
    "id": "tottori",
    "name": "鳥取城",
    "prefecture": "鳥取",
    "type": "castle",
    "lat": 35.5089,
    "lng": 134.2386,
    "stayDuration": "1.5 小時",
    "climbLevel": "mountain_mid",
    "climbLevelText": "⛰️ 梯郭山城（仁風閣與天球丸石垣預留 1.5h；若攻頂久松山頂需另加 1h）",
    "nearestStation": "鳥取駅",
    "stampLocation": "鳥取県立博物館 (9:00～17:00)",
    "closedDay": "Monday",
    "closedDayText": "週一休息 (休館時至鳥取市役所本廳舍1樓綜合窗口或管理室蓋章)",
    "backupStamp": "鳥取市役所本庁舎1階総合窓口または管理室",
    "openHours": "09:00 - 17:00",
    "transitInfo": "鳥取駅から100円バスくる梨「緑コース」で9分「仁風閣・県立博物館」下車徒歩5分",
    "reservationUrl": "",
    "notes": "名城編號 63。秀吉斷糧名城，天球丸圓形石垣與仁風閣。【寶可夢人孔蓋】：仁風閣旁與鳥取砂丘會館前設有鳥取限定『穿山鼠、皮卡丘』寶可夢彩色人孔蓋！山麓石垣與歷史館建議預留 1.5 小時；若挑戰久松山頂山上之丸需另加 1 小時。"
  },
  {
    "id": "gassan_toda",
    "name": "月山富田城",
    "prefecture": "島根",
    "type": "castle",
    "lat": 35.3614,
    "lng": 133.1906,
    "stayDuration": "2 ~ 2.5 小時",
    "climbLevel": "mountain_hard",
    "climbLevelText": "⛰️ 戰國五大險峻山城（七曲口險坡攻頂極耗體力，建議預留 2~2.5h）",
    "nearestStation": "安来駅",
    "stampLocation": "安来市立歴史資料館 (9:30～17:00)",
    "closedDay": "Tuesday",
    "closedDayText": "週二休息 (休館日館方於玄關前備有印章可蓋)",
    "backupStamp": "安来市立歴史資料館玄関前 (休館日可蓋)",
    "openHours": "09:30 - 17:00",
    "transitInfo": "山陰本線「安来駅」搭乘「広瀬行」黃色公車至「広瀬病院前」徒步15分抵資料館，登頂本丸需爬陡坡40分",
    "reservationUrl": "",
    "notes": "名城編號 65。尼子氏難攻不落巨大山城。自歷史資料館出發，經山中御殿、七曲口連續陡坡至山頂本丸，往返約需 80~100 分鐘山路步行，極耗體力，建議預留 2 ~ 2.5 小時，務必穿著防滑登山球鞋！"
  },
  {
    "id": "matsue",
    "name": "松江城",
    "prefecture": "島根",
    "type": "castle",
    "lat": 35.4753,
    "lng": 133.0506,
    "stayDuration": "1 小時",
    "climbLevel": "flat",
    "climbLevelText": "平山城（國寶現存天守平緩好走，基本預留 1h）",
    "nearestStation": "松江駅",
    "stampLocation": "松江城天守内受付カウンター (8:30～17:00)",
    "closedDay": "None",
    "closedDayText": "天守全年無休",
    "backupStamp": "",
    "openHours": "08:30 - 17:00",
    "transitInfo": "JR「松江駅」搭市營觀光巴士「ぐるっと松江レイクライン」約10分至「松江城（大手前）」即達",
    "reservationUrl": "",
    "notes": "名城編號 64。現存十二天守兼國寶五城之一「千鳥城」。二之丸、天守與興雲閣步道平緩好走，基本預留 1 小時（若搭乘護城河堀川遊覽船巡航建議增加至 1.5 小時）。"
  },
  {
    "id": "kaike_onsen",
    "name": "皆生溫泉 (米子市)",
    "prefecture": "鳥取",
    "type": "lodging",
    "lat": 35.4578,
    "lng": 133.3556,
    "stayDuration": "夜宿放鬆",
    "climbLevel": "lodging",
    "climbLevelText": "♨️ 海濱名湯（當日夜宿溫泉放鬆）",
    "nearestStation": "米子駅",
    "stampLocation": "溫泉街道 / 飯店設施",
    "closedDay": "None",
    "closedDayText": "住宿推薦點",
    "backupStamp": "",
    "openHours": "全天",
    "transitInfo": "JR 米子駅搭乘路線巴士往皆生溫泉方向約15~20分抵達溫泉街",
    "reservationUrl": "",
    "notes": "山陰屈指的海濱溫泉（米子之奧座敷），眺望日本海白沙海岸日落。【寶可夢人孔蓋】：皆生海濱公園（溫泉街旁海濱步道）設有鳥取限定『享受溫泉泡湯的穿山鼠』特色人孔蓋，夜宿泡湯時必拍！享用海鮮會席與高濃度海濱鹽湯。"
  },
  {
    "id": "yoshida_koriyama",
    "name": "郡山城 (吉田郡山城)",
    "prefecture": "廣島",
    "type": "castle",
    "lat": 34.6714,
    "lng": 132.7092,
    "stayDuration": "2 小時",
    "climbLevel": "mountain_hard",
    "climbLevelText": "⛰️ 全山大型山城要塞（毛利元就墓所及本丸登山健行，建議預留 2h）",
    "nearestStation": "広島バスセンター",
    "stampLocation": "安芸高田市歴史民俗博物館 (9:30～17:00)",
    "closedDay": "Tuesday",
    "closedDayText": "週二休息 (祝日開館，翌日休)",
    "backupStamp": "安芸高田市役所本庁 (休館日備案)",
    "openHours": "09:30 - 17:00",
    "transitInfo": "【推薦】廣島巴士中心搭客運往「吉田出張所」行 (約1小時20分) 至「安芸高田市役所前」下車步行5分；或JR藝備線「向原駅」轉計程車15分 (班次極少)",
    "reservationUrl": "",
    "notes": "名城編號 72。毛利元就百萬一心之城，整座山丘均為要塞防禦工事。自山麓博物館登山至毛利元就墓所、百萬一心石碑、山頂本丸，全程山林步道約需 1.5~2 小時，建議預留 2 小時。注意博物館週二休館！"
  },
  {
    "id": "hiroshima",
    "name": "廣島城",
    "prefecture": "廣島",
    "type": "castle",
    "lat": 34.4039,
    "lng": 132.4593,
    "stayDuration": "1 小時",
    "climbLevel": "flat",
    "climbLevelText": "平城（市中心平地天守，基本預留 1h）",
    "nearestStation": "広島駅",
    "stampLocation": "天守閣入口前通路 (9:00～16:30)",
    "closedDay": "None",
    "closedDayText": "無休 (12/29-12/31休)",
    "backupStamp": "",
    "openHours": "09:00 - 16:30",
    "transitInfo": "JR広島駅搭廣島電鐵1・2・6系統約14分「紙屋町東」下車北行徒步15分；或JR広島駅搭公車至「合同庁舎前」徒步8分",
    "reservationUrl": "",
    "notes": "名城編號 73。「鯉城」，毛利輝元所建，城內天守閣展示廣島武士文化與歷史。全境為平地，基本預留 1 小時。"
  },
  {
    "id": "iwakuni",
    "name": "岩國城",
    "prefecture": "山口",
    "type": "castle",
    "lat": 34.1747,
    "lng": 132.1764,
    "stayDuration": "1 小時",
    "climbLevel": "mountain_cable",
    "climbLevelText": "🚠 空中纜車山頂天守（纜車出站平路5分，基本預留 1h）",
    "nearestStation": "岩国駅",
    "stampLocation": "岩國城受付窓口 (9:00～16:45)",
    "closedDay": "None",
    "closedDayText": "無休 (遇纜車點檢時除外)",
    "backupStamp": "",
    "openHours": "09:00 - 16:45",
    "transitInfo": "山陽本線「岩国駅」或山陽新幹線「新岩国駅」搭公車約20分至「錦帯橋巴士中心」～徒步10分「山麓駅」轉搭登山纜車至「山頂駅」～徒步5分",
    "reservationUrl": "",
    "notes": "名城編號 74。搭乘岩國城空中纜車直達山頂橫山，出站後步道平坦約 5 分鐘抵達天守，觀景台視野遼闊直眺瀨戶內海與錦帶橋，基本預留 1 小時（含纜車上下與天守）。"
  },
  {
    "id": "tsuwano",
    "name": "津和野城",
    "prefecture": "島根",
    "type": "castle",
    "lat": 34.4642,
    "lng": 131.7686,
    "stayDuration": "1.5 小時",
    "climbLevel": "mountain_cable",
    "climbLevelText": "🚠 觀光纜車＋山稜林道（下纜車後步行爬坡15分，建議預留 1.5h）",
    "nearestStation": "津和野駅",
    "stampLocation": "津和野城跡観光リフト乗り場 (9:00～17:00)",
    "closedDay": "None",
    "closedDayText": "觀光纜車冬季或惡劣天候運休 (運休時印章移至津和野町鄉土館)",
    "backupStamp": "津和野町郷土館",
    "openHours": "09:00 - 17:00",
    "transitInfo": "JR 山口線「津和野駅」搭石見交通公車往「鴎外旧居・長野」約5分至「森」下車，步行10分抵纜車處，搭纜車(5分)後再步行15分至本丸",
    "reservationUrl": "",
    "notes": "名城編號 66。三本松城，山頂石垣壯麗，俯瞰山陰小京都紅瓦城下町。搭乘觀光單人纜車登頂後，仍需沿山林步道步行攀登約 15~20 分鐘抵達三十間台天守台，建議預留 1.5 小時。"
  },
  {
    "id": "hagi",
    "name": "萩城",
    "prefecture": "山口",
    "type": "castle",
    "lat": 34.4172,
    "lng": 131.3831,
    "stayDuration": "1 小時",
    "climbLevel": "flat",
    "climbLevelText": "平山城（指月公園平坦園區，基本預留 1h）",
    "nearestStation": "東萩駅",
    "stampLocation": "本丸入口料金所 (8:30～16:30)",
    "closedDay": "None",
    "closedDayText": "全年無休",
    "backupStamp": "指月公園料金所",
    "openHours": "08:30 - 16:30",
    "transitInfo": "JR 東萩駅或萩駅搭乘「萩循環まぁーるバス」（西回り路線）於「萩城跡・指月公園入口」下車徒歩3分",
    "reservationUrl": "",
    "notes": "名城編號 75。指月城，毛利防長三十七萬石雄藩本城。指月公園天守台、石垣與內堀平坦寬闊，散策輕鬆，基本預留 1 小時（若登指月山頂詰丸才需爬山）。"
  },
  {
    "id": "fukuyama",
    "name": "福山城",
    "prefecture": "廣島",
    "type": "castle",
    "lat": 34.4897,
    "lng": 133.3614,
    "stayDuration": "1 小時",
    "climbLevel": "flat",
    "climbLevelText": "平山城（福山車站北口直出0距離，基本預留 1h）",
    "nearestStation": "福山駅",
    "stampLocation": "福山城天守閣内 (9:00～17:00)",
    "closedDay": "Monday",
    "closedDayText": "週一休息 (祝日翌日休，12/28-12/31休)",
    "backupStamp": "福山城博物館前",
    "openHours": "09:00 - 17:00",
    "transitInfo": "山陽新幹線・山陽本線「福山駅」北口出站步行 5 分鐘即達 (全日本離新幹線最近的城池！)",
    "reservationUrl": "",
    "notes": "名城編號 71。水野勝成所築，全日本唯一北側覆蓋黑鐵板之「鐵板張天守」、伏見櫓。就在新幹線福山站北口正前方，平坦好走，基本預留 1 小時。"
  },
  {
    "id": "yunogo_onsen",
    "name": "湯郷溫泉 (美作市)",
    "prefecture": "岡山",
    "type": "lodging",
    "lat": 35.0064,
    "lng": 134.0925,
    "stayDuration": "夜宿放鬆",
    "climbLevel": "lodging",
    "climbLevelText": "♨️ 千年白鷺名湯（當日夜宿溫泉放鬆）",
    "nearestStation": "津山駅",
    "stampLocation": "溫泉街各大旅館 / 湯郷鷺溫泉館",
    "closedDay": "None",
    "closedDayText": "住宿推薦點 (鷺溫泉館全天開放)",
    "backupStamp": "",
    "openHours": "全天",
    "transitInfo": "JR 津山駅搭乘「宇野巴士」往湯郷溫泉約35分直達溫泉街；或 JR 姫新線「林野駅」搭公車約10分",
    "reservationUrl": "https://spa-yunogo.or.jp/",
    "notes": "美作三湯之一，千年白鷺古湯，弱鹼性美肌名湯。津山城參觀後夜宿首選，和風老街悠閒散步。"
  },
  {
    "id": "tamatsukuri_onsen",
    "name": "玉造溫泉 (松江市)",
    "prefecture": "島根",
    "type": "lodging",
    "lat": 35.4194,
    "lng": 133.0108,
    "stayDuration": "夜宿放鬆",
    "climbLevel": "lodging",
    "climbLevelText": "♨️ 日本最古美肌神湯（當日夜宿溫泉放鬆）",
    "nearestStation": "玉造溫泉駅",
    "stampLocation": "玉湯川溫泉街旅館 / 湯藥師廣場 / 玉作湯神社",
    "closedDay": "None",
    "closedDayText": "住宿推薦點",
    "backupStamp": "",
    "openHours": "全天",
    "transitInfo": "JR 松江駅搭山陰本線至「玉造溫泉駅」(8分) 轉接駁車5分；或松江站前搭路線巴士直達約25分",
    "reservationUrl": "https://tamayado.com/",
    "notes": "出雲神話八尺瓊勾玉發祥地，日本最古美肌化妝水神湯，沿玉湯川有宮橋、免費足湯與結緣神社。"
  },
  {
    "id": "tomonoura_onsen",
    "name": "鞆之浦溫泉 (福山市)",
    "prefecture": "廣島",
    "type": "lodging",
    "lat": 34.3828,
    "lng": 133.3831,
    "stayDuration": "夜宿放鬆",
    "climbLevel": "lodging",
    "climbLevelText": "♨️ 波妞古港海景名湯（當日夜宿溫泉放鬆）",
    "nearestStation": "福山駅",
    "stampLocation": "鞆之浦港町各大飯店 / 常夜燈旁海景旅館",
    "closedDay": "None",
    "closedDayText": "住宿推薦點",
    "backupStamp": "",
    "openHours": "全天",
    "transitInfo": "JR 福山駅南口 5 號月台搭乘「鞆鐵道巴士」往鞆港方向約30分直達溫泉街",
    "reservationUrl": "https://tomonoura.np-inc.jp/",
    "notes": "宮崎駿《崖上的波妞》取景舞台、江戶常夜燈古港，對望仙醉島絕景海景露天風呂與瀨戶內海海鮮。"
  },
  {
    "id": "okayama_airport",
    "name": "岡山桃太郎機場 (OKJ)",
    "prefecture": "岡山",
    "type": "custom",
    "lat": 34.7578,
    "lng": 133.8553,
    "stayDuration": "40分 ~ 1 小時",
    "climbLevel": "transit",
    "climbLevelText": "✈️ 機場入境／轉乘利木津巴士",
    "nearestStation": "岡山駅",
    "stampLocation": "機場觀光案內所 / 國際線入境大廳",
    "closedDay": "None",
    "closedDayText": "虎航班機起降",
    "backupStamp": "",
    "openHours": "全天 (配合航班營運)",
    "transitInfo": "出關後於巴士乘車處搭乘「岡山駅西口行」利木津巴士直達岡山車站 (約30分，單程780円)",
    "reservationUrl": "https://www.okayama-airport.org/access/bus",
    "notes": "台灣虎航直飛起降機場。入境後搭乘直達巴士直奔岡山站前商圈，展開壯遊！"
  },
  {
    "id": "chiyagyu_bisai",
    "name": "鉄板焼 備彩 (千屋牛)",
    "prefecture": "岡山",
    "type": "custom",
    "lat": 34.6648,
    "lng": 133.9185,
    "stayDuration": "1.5 小時",
    "climbLevel": "gourmet",
    "climbLevelText": "🥩 頂級和牛美食（岡山車站直結）",
    "nearestStation": "岡山駅",
    "stampLocation": "飯店2F餐廳",
    "closedDay": "None",
    "closedDayText": "無休",
    "backupStamp": "",
    "openHours": "午餐 11:30~14:30 / 晚餐 17:30~21:30 (L.O. 20:30)",
    "transitInfo": "JR 岡山站 2F 聯通步道直結「岡山格蘭比亞大飯店 (Hotel Granvia Okayama)」2F",
    "reservationUrl": "https://jrwest-hotels.jp/tw/granvia-okayama/restaurant/bisai/",
    "notes": "岡山夢幻和牛「千屋牛」特選鐵板燒。直結岡山車站 2F，極致交通便利。極度推薦排在【Day 1 晚餐】（虎航抵達Check-in後）或【Day 8 午餐】返台前慶功！"
  },
  {
    "id": "chiyagyu_kuya",
    "name": "鉄板焼 空也 (千屋牛)",
    "prefecture": "岡山",
    "type": "custom",
    "lat": 34.6655,
    "lng": 133.9235,
    "stayDuration": "1.5 小時",
    "climbLevel": "gourmet",
    "climbLevelText": "🥩 頂級和牛美食（西川綠道公園商圈）",
    "nearestStation": "岡山駅",
    "stampLocation": "餐廳櫃台",
    "closedDay": "Sunday",
    "closedDayText": "週日公休 (或依預約不定休)",
    "backupStamp": "",
    "openHours": "晚餐 18:00~23:00 (L.O. 22:30)",
    "transitInfo": "JR 岡山站東口出站步行約 5~7 分鐘 (岡山市北區平和町 1-11)",
    "reservationUrl": "https://teppan-ku-ya.gorp.jp/",
    "notes": "岡山市區隱密職人鐵板燒名店，專精 A5 頂級千屋牛、黑毛和牛與海鮮鐵板料理。適合【Day 1 晚餐】散步至西川綠道公園商圈享用。"
  },
  {
    "id": "tottori_takumi",
    "name": "たくみ割烹店 (鳥取和牛元祖涮涮鍋)",
    "prefecture": "鳥取",
    "type": "custom",
    "lat": 35.4963,
    "lng": 134.2267,
    "stayDuration": "1 ~ 1.5 小時",
    "climbLevel": "gourmet",
    "climbLevelText": "🥩 日本涮涮鍋發祥元祖（鳥取站北口步行4分）",
    "nearestStation": "鳥取駅",
    "stampLocation": "店內櫃台 / 鳥取民藝館旁",
    "closedDay": "Wednesday",
    "closedDayText": "週三公休 (Day 3 為週五正常營業！)",
    "backupStamp": "",
    "openHours": "午餐 11:30~14:00 / 晚餐 17:00~21:00 (L.O. 20:00)",
    "transitInfo": "JR 鳥取站北口出站步行僅 4 分鐘 (鳥取市榮町 652，鳥取民藝美術館旁)",
    "reservationUrl": "https://www.tottori-mingei.jp/takumikappou.html",
    "notes": "【全日本涮涮鍋 (すすぎ鍋/しゃぶしゃぶ) 發祥起源店】！採用最高品質鳥取和牛薄切，搭配民藝陶器裝盛。極度推薦排入【Day 3 午餐】（出鳥取站先吃和牛午餐，再攻鳥取城，傍晚進皆生溫泉，完全不跟當晚溫泉海鮮晚餐衝突！神級排程首選）。"
  },
  {
    "id": "tottori_tsubomi",
    "name": "鉄板焼 つぼみ (米子鳥取和牛)",
    "prefecture": "鳥取",
    "type": "custom",
    "lat": 35.432,
    "lng": 133.334,
    "stayDuration": "1.5 小時",
    "climbLevel": "gourmet",
    "climbLevelText": "🥩 大山黑牛特選鐵板燒（米子角盤町）",
    "nearestStation": "米子駅",
    "stampLocation": "餐廳櫃台",
    "closedDay": "Sunday",
    "closedDayText": "週日公休 (或不定休，需預約)",
    "backupStamp": "",
    "openHours": "午餐 11:30~14:30 / 晚餐 17:30~22:00",
    "transitInfo": "JR 米子站車程 5 分鐘（搭市內公車至角盤町徒步2分，或從皆生溫泉車程約 10~15 分鐘）",
    "reservationUrl": "https://teppan-tsubomi.com/menu/",
    "notes": "米子市區頂級鐵板燒，主打鳥取和牛之王「大山黑牛」牛排。可排在【Day 3 晚餐】。注意：若當晚皆生溫泉旅館訂「一泊二食會席」，晚餐會衝突；若要吃つぼみ，溫泉飯店請訂「純一泊朝食」。"
  },
  {
    "id": "hiroshima_jinseki",
    "name": "鉄板焼 神石 (廣島牛・Granvia 21F)",
    "prefecture": "廣島",
    "type": "custom",
    "lat": 34.398,
    "lng": 132.476,
    "stayDuration": "1.5 小時",
    "climbLevel": "gourmet",
    "climbLevelText": "🥩 廣島和牛高空夜景鐵板燒（廣島站直結21F）",
    "nearestStation": "広島駅",
    "stampLocation": "飯店21F餐廳",
    "closedDay": "None",
    "closedDayText": "無休",
    "backupStamp": "",
    "openHours": "午餐 11:30~14:30 / 晚餐 17:00~21:30 (L.O. 20:30)",
    "transitInfo": "JR 廣島站新幹線口 (北口) 直結「廣島格蘭比亞大飯店 (Hotel Granvia Hiroshima)」頂樓 21F",
    "reservationUrl": "https://jrwest-hotels.jp/granvia-hiroshima/restaurant/jinseki/",
    "notes": "坐擁 21 樓廣島市區高空百萬夜景，主打特選廣島牛、神石牛頂級鐵板燒。推薦排在【Day 6 晚餐】（若今晚住廣島站前，攻完城回站前搭電梯上樓直吃，吃完下樓即睡，零交通成本）！"
  },
  {
    "id": "hiroshima_atago",
    "name": "鉄板焼 愛宕 (廣島牛・ANA 1F)",
    "prefecture": "廣島",
    "type": "custom",
    "lat": 34.39,
    "lng": 132.458,
    "stayDuration": "1.5 小時",
    "climbLevel": "gourmet",
    "climbLevelText": "🥩 廣島牛比婆牛星級鐵板燒（平和公園旁）",
    "nearestStation": "袋町駅 / 広島駅",
    "stampLocation": "飯店1F餐廳",
    "closedDay": "None",
    "closedDayText": "無休",
    "backupStamp": "",
    "openHours": "午餐 11:30~14:30 (L.O. 14:00) / 晚餐 17:30~21:30 (L.O. 20:30)",
    "transitInfo": "廣島電鐵宇品線「袋町」站步行 2 分鐘，ANA皇冠假日酒店1F（距和平紀念公園/原爆圓頂徒步僅 7 分鐘）",
    "reservationUrl": "https://www.anacrowneplaza-hiroshima.jp/restaurants/atago/",
    "notes": "廣島名店，主打廣島牛、比婆牛特選鐵板燒。推薦排在【Day 6 晚餐】（下午參觀完廣島城、原爆圓頂與和平公園後，步行 5~7 分鐘即可優雅入座，吃完逛本通商圈）。"
  },
  {
    "id": "izumo_taisha",
    "name": "出雲大社 (Izumo Taisha)",
    "prefecture": "島根",
    "type": "custom",
    "lat": 35.3995,
    "lng": 132.6859,
    "stayDuration": "1.5 ~ 2 小時",
    "climbLevel": "shrine",
    "climbLevelText": "⛩️ 日本神話最高殿堂・第一結緣神社",
    "nearestStation": "出雲市駅 / 出雲大社前駅",
    "stampLocation": "拜殿 / 神樂殿授與所",
    "closedDay": "None",
    "closedDayText": "境內全天開放 (授與所 08:30~17:00)",
    "backupStamp": "",
    "openHours": "06:00 - 18:00",
    "transitInfo": "JR 出雲市站轉一畑巴士約 25 分直達正門前，或一畑電車「出雲大社前站」徒步 7 分",
    "reservationUrl": "https://izumooyashiro.or.jp/",
    "notes": "日本神話之巔峰。國寶大社造本殿、神樂殿重達 5.2 噸日本最大注連繩。農曆十月「神在月」全國八百萬神明聚首，求良緣、事業與平安極致靈驗。"
  },
  {
    "id": "itsukushima_jinja",
    "name": "嚴島神社 (宮島・世界遺產)",
    "prefecture": "廣島",
    "type": "custom",
    "lat": 34.296,
    "lng": 132.3198,
    "stayDuration": "2 ~ 3 小時",
    "climbLevel": "shrine",
    "climbLevelText": "⛩️ 世界文化遺產・海上大鳥居與朱紅寢殿",
    "nearestStation": "宮島口駅 / 宮島碼頭",
    "stampLocation": "神社授與所",
    "closedDay": "None",
    "closedDayText": "全年無休",
    "backupStamp": "",
    "openHours": "06:30 - 18:00 (依季節微調)",
    "transitInfo": "JR 廣島站搭山陽本線至「宮島口站」(26分)，徒步至碼頭搭 JR 渡輪 10 分抵宮島，再步行 10 分即達",
    "reservationUrl": "https://www.itsukushimajinja.jp/",
    "notes": "日本三景之一、世界文化遺產。潮漲時宛如浮於海面，潮退可徒步走向高達 16 公尺的海上大鳥居底下觸摸祈願。參道商店街烤牡蠣與炸紅葉饅頭必嚐！"
  },
  {
    "id": "kibitsu_jinja",
    "name": "吉備津神社 (Kibitsu Jinja)",
    "prefecture": "岡山",
    "type": "custom",
    "lat": 34.6698,
    "lng": 133.8504,
    "stayDuration": "1 ~ 1.5 小時",
    "climbLevel": "shrine",
    "climbLevelText": "⛩️ 桃太郎傳說起源・國寶本殿與 398m 木造大迴廊",
    "nearestStation": "吉備津駅",
    "stampLocation": "神社社務所",
    "closedDay": "None",
    "closedDayText": "全年無休",
    "backupStamp": "",
    "openHours": "05:00 - 18:00 (社務所 08:30~16:30)",
    "transitInfo": "JR 岡山站搭吉備線 (桃太郎線) 約 17 分抵達「吉備津站」，步行約 10 分即達 (在岡山前往鬼ノ城的同一條鐵路線上！)",
    "reservationUrl": "http://www.kibitujinja.com/",
    "notes": "桃太郎退治惡鬼溫羅之發祥神社。全日本唯一「吉備津造」國寶比翼入母屋造本殿，長達 398 公尺沿山勢起伏之木造大迴廊美得令人窒息。神祕鳴釜神事亦聞名全國。"
  },
  {
    "id": "yaegaki_jinja",
    "name": "八重垣神社 (Yaegaki Jinja)",
    "prefecture": "島根",
    "type": "custom",
    "lat": 35.4287,
    "lng": 133.0734,
    "stayDuration": "1 小時",
    "climbLevel": "shrine",
    "climbLevelText": "⛩️ 須佐之男斬八岐大蛇結緣地・鏡之池紙張硬幣水占",
    "nearestStation": "松江駅",
    "stampLocation": "社務所",
    "closedDay": "None",
    "closedDayText": "全年無休",
    "backupStamp": "",
    "openHours": "09:00 - 17:00",
    "transitInfo": "JR 松江站搭乘市營巴士（八重垣神社行）約 20 分直達神社正門 (離玉造溫泉開車僅 15 分)",
    "reservationUrl": "https://yaegakijinja.or.jp/",
    "notes": "須佐之男命與奇稻田姬結緣成婚之所。境內「鏡之池」為全日本少女最嚮往的水占卜：將許願硬幣置於和紙放流水面，紙沉速度（15分內）與漂流遠近象徵良緣快慢與對象遠近，極度靈驗！"
  },
  {
    "id": "taikodani_inari",
    "name": "太鼓谷稻成神社 (Taikodani Inari)",
    "prefecture": "島根",
    "type": "custom",
    "lat": 34.4607,
    "lng": 131.7681,
    "stayDuration": "1 小時",
    "climbLevel": "shrine",
    "climbLevelText": "⛩️ 日本五大稻荷之一・千本鳥居紅色隧道",
    "nearestStation": "津和野駅",
    "stampLocation": "社務所授與所",
    "closedDay": "None",
    "closedDayText": "全年無休",
    "backupStamp": "",
    "openHours": "全天開放 (祈禱授與 08:00~17:00)",
    "transitInfo": "JR 津和野站步行約 20 分至表參道口，穿過千本鳥居階梯步道約 15 分登頂（就在津和野城山麓旁！）",
    "reservationUrl": "http://taikodani.jp/",
    "notes": "日本五大稻荷神社之一。全日本唯一漢字寫作「稻成」的神社，寓意『願望開花結果、大功告成』。約千座鮮紅鳥居綿延築成朱紅隧道，山頂俯瞰津和野紅瓦城下町。"
  },
  {
    "id": "hakuto_jinja",
    "name": "白兔神社 (Hakuto Jinja)",
    "prefecture": "鳥取",
    "type": "custom",
    "lat": 35.5348,
    "lng": 134.1352,
    "stayDuration": "1 小時",
    "climbLevel": "shrine",
    "climbLevelText": "⛩️ 因幡之白兔神話發祥・日本最強白兔結緣與美肌",
    "nearestStation": "鳥取駅",
    "stampLocation": "社務所",
    "closedDay": "None",
    "closedDayText": "全年無休",
    "backupStamp": "",
    "openHours": "09:00 - 16:00",
    "transitInfo": "JR 鳥取站搭乘日之丸巴士（鹿野行）約 40 分於「白兔神社前」下車直達海濱",
    "reservationUrl": "https://hakutojinja.jp/",
    "notes": "日本古代神話《因幡之白兔》舞台。主祀協助大國主命與八上姬結下良緣的白兔神，境內佈滿可愛兔子石像，御守白兔「結緣石」供人祈福，亦是保佑皮膚健康光滑的著名神社。"
  },
  {
    "id": "tamatsukuri_yu_jinja",
    "name": "玉作湯神社 (Tamatsukuri Yu Jinja)",
    "prefecture": "島根",
    "type": "custom",
    "lat": 35.4147,
    "lng": 133.0089,
    "stayDuration": "40 分鐘",
    "climbLevel": "shrine",
    "climbLevelText": "⛩️ 溫泉街守護神・願之石與葉之石奇蹟御守",
    "nearestStation": "玉造溫泉駅",
    "stampLocation": "社務所",
    "closedDay": "None",
    "closedDayText": "全年無休",
    "backupStamp": "",
    "openHours": "09:00 - 17:00",
    "transitInfo": "位於玉造溫泉街最深處，從各大溫泉旅館徒步 5~10 分鐘即達",
    "reservationUrl": "https://tamayado.com/spot/tamatsukuriyujinja",
    "notes": "祭祀溫泉與古代勾玉工匠之神。在此求取「葉之石（叶い石）」，至境內天然靈石「願之石（願い石）」碰觸並祈願，製成專屬個人御守，非常受到旅人喜愛。"
  },
  {
    "id": "motonosumi_jinja",
    "name": "元乃隅神社 (Motonosumi Jinja)",
    "prefecture": "山口",
    "type": "custom",
    "lat": 34.4258,
    "lng": 131.0603,
    "stayDuration": "1 ~ 1.5 小時",
    "climbLevel": "shrine",
    "climbLevelText": "⛩️ CNN評選日本最美31景・123座斷崖龍宮海景紅鳥居",
    "nearestStation": "長門古市駅 / 長門市駅",
    "stampLocation": "社務所 / 鳥居頂上賽錢箱",
    "closedDay": "None",
    "closedDayText": "夜間禁止進入",
    "backupStamp": "",
    "openHours": "05:30 - 17:30",
    "transitInfo": "JR 山陰本線「長門古市站」搭計程車約 20 分鐘；或由萩市區租車自駕約 50 分鐘 (適合12~14天行程山口段延伸)",
    "reservationUrl": "https://motonosumi.com/",
    "notes": "CNN 評選日本最美絕景之一！123 座紅色鳥居沿著青翠山崖一路蜿蜒奔向湛藍日本海與龍宮潮吹。參道頂部 6 公尺高的大鳥居上方設有『全日本最難投中賽錢箱』，投進代表願望必能實現！"
  },
  {
    "id": "kibitsuhiko_jinja",
    "name": "吉備津彥神社 (Kibitsuhiko Jinja)",
    "prefecture": "岡山",
    "type": "custom",
    "lat": 34.6787,
    "lng": 133.8601,
    "stayDuration": "45 分鐘",
    "climbLevel": "shrine",
    "climbLevelText": "⛩️ 備前國一之宮・桃太郎主神與朝日之宮白桃御守",
    "nearestStation": "備前一宮駅",
    "stampLocation": "神社社務所授與所",
    "closedDay": "None",
    "closedDayText": "全年無休",
    "backupStamp": "",
    "openHours": "06:00 - 18:00 (社務所 08:30~17:00)",
    "transitInfo": "JR 岡山站搭吉備線 (桃太郎線) 約 11 分抵達「備前一宮站」，出站徒步 3 分鐘即達 (與鬼ノ城、吉備津神社同一條吉備鐵路線！)",
    "reservationUrl": "http://www.kibitsuhiko.or.jp/",
    "notes": "備前國一之宮，主祀大吉備津日子命（桃太郎傳說原型主神）。夏至清晨朝陽正對鳥居與本殿升起，被尊為『朝日之宮』。境內千年平安杉、神池龜島與隨神門仙氣環繞，必求超人氣立體白桃陶籤與桃太郎御守！"
  },
  {
    "id": "kurashiki_bikan",
    "name": "倉敷美觀地區 (Kurashiki Bikan)",
    "prefecture": "岡山",
    "type": "custom",
    "lat": 34.5954,
    "lng": 133.7716,
    "stayDuration": "2 ~ 3 小時",
    "climbLevel": "scenic",
    "climbLevelText": "🏞️ 江戶天領白壁土藏・倉敷川搖櫓遊船與大原美術館",
    "nearestStation": "倉敷駅",
    "stampLocation": "倉敷館觀光案內所",
    "closedDay": "None",
    "closedDayText": "店家多於週一公休，街區全天開放",
    "backupStamp": "",
    "openHours": "街區全天開放 (店家與展館約 10:00~17:00)",
    "transitInfo": "JR 岡山站搭山陽本線/伯備線 17 分鐘抵「倉敷站」，南口出站徒步 10 分鐘即達 (高梁備中松山城往返岡山必經！)",
    "reservationUrl": "https://www.kurashiki-tabi.jp/see-kurashiki/",
    "notes": "米其林二星評價歷史街區。白壁宅邸、黑瓦菱形格櫺磚牆倒映於楊柳搖曳的倉敷川，乘木造川舟穿梭江戶時光。大原美術館收藏莫內、艾爾葛雷柯名畫，亦有帆布與紙膠帶文創本店。"
  },
  {
    "id": "tottori_sakyu",
    "name": "鳥取砂丘 & 砂之美術館 (Tottori Sand Dunes)",
    "prefecture": "鳥取",
    "type": "custom",
    "lat": 35.5418,
    "lng": 134.2274,
    "stayDuration": "2 ~ 2.5 小時",
    "climbLevel": "scenic",
    "climbLevelText": "🏞️ 日本最大海岸沙丘・騎駱駝與世界唯一砂雕美術館",
    "nearestStation": "鳥取駅",
    "stampLocation": "砂丘會館 / 砂之美術館案內所",
    "closedDay": "None",
    "closedDayText": "砂丘全天開放 (砂之美術館換展期休館)",
    "backupStamp": "",
    "openHours": "砂丘全天 / 砂之美術館 09:00~18:00",
    "transitInfo": "JR 鳥取站前 0 號巴士月台搭乘公車約 20 分直達「砂丘會館」或「砂之美術館前」",
    "reservationUrl": "https://www.sand-museum.jp/",
    "notes": "日本國家天然紀念物。歷經十萬年海風與千代川沙土堆積之雄偉奇景。攀登『馬背』頂峰俯瞰日本海壯闊海景；一旁砂之美術館為世界首座以砂雕為主題之室內美術館，每期作品鬼斧神工。"
  },
  {
    "id": "adachi_museum",
    "name": "足立美術館 (Adachi Museum of Art)",
    "prefecture": "島根",
    "type": "custom",
    "lat": 35.378,
    "lng": 133.1979,
    "stayDuration": "2 小時",
    "climbLevel": "scenic",
    "climbLevelText": "🏞️ 連續 21 年日本第一庭園・橫山大觀名畫與借景山水",
    "nearestStation": "安来駅",
    "stampLocation": "美術館入口大廳",
    "closedDay": "None",
    "closedDayText": "年中無休",
    "backupStamp": "",
    "openHours": "09:00 - 17:30 (冬季至 17:00)",
    "transitInfo": "JR 山陰本線「安來站」出站即有免費接駁專車約 20 分直達 (攻月山富田城的安來站同站！)",
    "reservationUrl": "https://www.adachi-museum.or.jp/",
    "notes": "被美國權威庭園雜誌連續 21 年評選為全日本第一名庭園。借景遠方勝山山脈，白砂青松庭、苔庭枯山水如一幅活生生的日本畫。館內收藏多達 1,500 件以橫山大觀為首的現代日本畫巨作。"
  },
  {
    "id": "onomichi_senkoji",
    "name": "尾道千光寺公園 & 貓之細道",
    "prefecture": "廣島",
    "type": "custom",
    "lat": 34.4098,
    "lng": 133.1947,
    "stayDuration": "2 ~ 3 小時",
    "climbLevel": "scenic",
    "climbLevelText": "🏞️ 瀨戶內海尾道水道絕景・千光寺纜車與貓之細道散策",
    "nearestStation": "尾道駅",
    "stampLocation": "千光寺山頂纜車站 / 觀光案內所",
    "closedDay": "None",
    "closedDayText": "全年無休",
    "backupStamp": "",
    "openHours": "公園全天開放 / 千光寺纜車 09:00~17:15",
    "transitInfo": "JR 尾道站搭市內巴士 5 分至「長江口」，搭千光寺纜車 3 分鐘攻頂 (位於廣島與福山之間！)",
    "reservationUrl": "https://www.ononavi.jp/",
    "notes": "瀨戶內海坡道小鎮。搭乘纜車登頂眺望尾道水道、向島與島波海道諸島；下山漫步穿梭於『文學小路』與『貓之細道』，沿途坡道老屋咖啡廳與慵懶親人貓咪，文藝氣息滿溢。"
  },
  {
    "id": "matsue_horikawa",
    "name": "松江城 堀川遊覽船",
    "prefecture": "島根",
    "type": "custom",
    "lat": 35.4745,
    "lng": 133.052,
    "stayDuration": "1 小時",
    "climbLevel": "scenic",
    "climbLevelText": "🏞️ 穿梭國寶松江城護城河・低頭過橋趣味木造小舟",
    "nearestStation": "松江駅",
    "stampLocation": "卡拉闊路乘船場 (大手前)",
    "closedDay": "None",
    "closedDayText": "年中無休 (冬季有暖爐桌被爐船)",
    "backupStamp": "",
    "openHours": "09:00 - 17:00 (依季節變動，每15分鐘一班)",
    "transitInfo": "位於松江城大手前，松江市營巴士レイクライン「大手前堀川遊覧船乗場」下車即達",
    "reservationUrl": "https://www.matsue-horikawameguri.jp/",
    "notes": "環繞松江城內外護城河一圈（約 50 分鐘）。途經 16 座風格各異的橋樑，遇到極低矮橋樑時，整艘小舟的遮雨頂棚會自動降下，所有人需彎腰縮頭，充滿互動趣味！冬季更提供暖爐被爐 (こたつ) 體驗。"
  },
  {
    "id": "sakaiminato_mizuki",
    "name": "境港水木茂大道 (鬼太郎妖怪老街)",
    "prefecture": "鳥取",
    "type": "custom",
    "lat": 35.5503,
    "lng": 133.2325,
    "stayDuration": "2 小時",
    "climbLevel": "scenic",
    "climbLevelText": "🏞️ 鬼太郎妖怪老街・177尊青銅像與妖怪神社",
    "nearestStation": "境港駅",
    "stampLocation": "水木茂紀念館 / 境港觀光案內所",
    "closedDay": "None",
    "closedDayText": "大道全天開放 (水木茂紀念館通常週二休)",
    "backupStamp": "",
    "openHours": "大道全天 / 紀念館 09:30~17:00",
    "transitInfo": "JR 米子站搭乘境線「妖怪彩繪列車」約 45 分抵終點「境港站」，出站即達大道 (米子皆生溫泉旁！)",
    "reservationUrl": "https://mizuki.sakaiminato.net/",
    "notes": "日本妖怪漫畫之神水木茂故鄉。全長 800 公尺街道兩側林立 177 尊栩栩如生的妖怪青銅像，設有妖怪神社、妖怪郵筒與水木茂紀念館。亦是西日本最大境港松葉蟹紅楚蟹海鮮集散地！"
  },
  {
    "id": "pokemon_center_hiroshima",
    "name": "寶可夢中心 廣島 (Pokémon Center)",
    "prefecture": "廣島",
    "type": "custom",
    "lat": 34.3962,
    "lng": 132.4571,
    "stayDuration": "1 小時",
    "climbLevel": "anime",
    "climbLevelText": "⚡ 中國地區唯一官方直營・紅色暴鯉龍與限定周邊",
    "nearestStation": "紙屋町西駅 / 広島駅",
    "stampLocation": "店內櫃台 / SOGO 6F",
    "closedDay": "None",
    "closedDayText": "無休 (依百貨營業)",
    "backupStamp": "",
    "openHours": "10:00 - 19:30",
    "transitInfo": "廣島電鐵「紙屋町西」站出站即達（そごう広島店 本館6F）；從廣島城南門步行約 8 分鐘，距原爆圓頂步行僅 3 分鐘",
    "reservationUrl": "https://www.pokemon.co.jp/shop/pokecen/hiroshima/",
    "notes": "全中國地區唯一官方直營寶可夢中心！鎮店神獸為『紅色暴鯉龍』與皮卡丘，販售廣島限定紅色暴鯉龍皮卡丘玩偶、全系列卡牌與周邊。排在廣島城與和平公園之間步行順遊！"
  },
  {
    "id": "hiroshima_peace_museum",
    "name": "廣島和平紀念資料館 (原爆資料館)",
    "prefecture": "廣島",
    "type": "custom",
    "lat": 34.3916,
    "lng": 132.4526,
    "stayDuration": "1.5 小時",
    "climbLevel": "museum",
    "climbLevelText": "🕊️ 世界和平地標・米其林三星歷史見證",
    "nearestStation": "原爆ドーム前駅 / 平和記念公園",
    "stampLocation": "本館1樓綜合案內所",
    "closedDay": "None",
    "closedDayText": "無休 (12/30-12/31休)",
    "backupStamp": "",
    "openHours": "08:30 - 18:00 (閉館前30分停止入館)",
    "transitInfo": "廣島電鐵至「原爆ドーム前」徒步 5 分；從 SOGO 寶可夢中心往南穿過和平公園徒步約 5~7 分鐘即達",
    "reservationUrl": "https://hpmmuseum.jp/",
    "notes": "米其林三星評鑑。丹下健三設計之和平紀念公園核心，陳列原爆歷史見證、被爆者遺物與祈念和平鐘。館前慰靈碑正對原爆圓頂軸線。門票 200 円，建議預留 1.5 小時莊嚴參觀。"
  }
];

// 預設推薦行程動線 (出發日期自 2027-01-13 起算；虎航岡山進出・12名城+4名湯+和牛名店+寶可夢與和平資料館)
const DEFAULT_ITINERARY = [
  {
    "dayNumber": 1,
    "title": "Day 1：抵達岡山・機場 ➔ 住宿 ➔ 和牛 ➔ 逛街",
    "date": "2027-01-13",
    "baseStation": "岡山桃太郎機場 / 岡山駅",
    "lodging": "岡山站前飯店 (大和Roynet / 格蘭比亞 / 三井花園)",
    "notes": "• 【機場抵達】：搭乘台灣虎航下午抵達岡山桃太郎機場 (OKJ)。出關後於 2 號乘車處搭乘利木津巴士約 30 分鐘直達岡山站西口 (單程 780 円，可刷 IC 卡)。\n• 【住宿 Check-in】：進駐岡山站前飯店 (格蘭比亞 / 大和Roynet / 三井花園) 辦理入住手續並放下大件行李。\n• 【和牛晚餐 (岡山千屋牛)】：前往岡山格蘭比亞 2F 直結之「鉄板焼 備彩」，零距離品嚐日本最古老血統和牛——岡山千屋牛頂級鐵板燒。\n• 【商圈漫遊 & 逛街】：餐後漫步西日本最大級「AEON Mall Okayama」(營業至 21:00，350間店鋪) 逛街採買藥妝物資，無其他多餘奔波行程，早點休息為明日 12 名城巡禮儲備體力！",
    "spotIds": [
      "okayama_airport",
      "chiyagyu_bisai",
      "okayama_aeon",
      "okayama_hotel"
    ]
  },
  {
    "dayNumber": 2,
    "title": "Day 2：吉備古國與美作名湯",
    "date": "2027-01-14",
    "baseStation": "岡山駅 / 津山駅",
    "lodging": "湯郷溫泉 和風旅館 (美作市)",
    "notes": "• 【鬼ノ城・登山步道 (建議預留 1.5~2h)】：晨間自岡山搭 JR 吉備線至總社站，搭計程車約 30 分攻登古代神秘山城鬼ノ城。山頂西門石垣與步道巡禮視野極佳，下車時務必先與司機約定下山回程時間！\n• 【津山城・平山城 (基本預留 1h)】：午後搭 JR 津山線至津山站，步行 10 分攻登津山城（鶴山公園備中櫓，園區平緩好走）。\n• 【湯郷溫泉・夜宿】：傍晚於津山站前搭宇野巴士（約 35 分）直達湯郷溫泉，入住和風旅館，享受千年美肌白鷺古湯與老街散策。",
    "spotIds": [
      "kinojo",
      "tsuyama",
      "yunogo_onsen"
    ]
  },
  {
    "dayNumber": 3,
    "title": "Day 3：因幡鳥取與山陰海濱名湯",
    "date": "2027-01-15",
    "baseStation": "津山駅 / 鳥取駅 / 米子駅",
    "lodging": "皆生溫泉 海濱旅館 (米子市)",
    "notes": "• 【跨越因幡鳥取】：晨間自湯郷出發經津山，搭乘 JR 因美線直通北上抵達鳥取站 (約 11:30~12:00 抵達)。\n• 【和牛午餐神級推薦 (鳥取和牛元祖)】：出鳥取站北口步行僅 4 分鐘，前往日本牛肉涮涮鍋起源發祥店「たくみ割烹店」享用鳥取和牛元祖涮涮鍋 (すすぎ鍋) 或味噌牛肉鍋！\n• 【鳥取城・天球丸石垣 (建議預留 1.5h)】：午後搭百圓公車至仁風閣與鳥取城跡，參觀特殊圓形天球丸石垣與歷史館。\n• 【寶可夢人孔蓋巡禮 (穿山鼠)】：\n  1. 鳥取市 (鳥取城/砂丘)：鳥取砂丘會館前 / 仁風閣旁有鳥取限定「穿山鼠、皮卡丘」寶可夢彩繪人孔蓋！\n  2. 米子市 (皆生溫泉)：皆生海濱公園（溫泉街旁海濱步道）設有「享受溫泉泡湯的穿山鼠」特色人孔蓋，抵達溫泉旅館散步時必拍！\n• 【山陰海岸特急】：午後搭乘特急超級松風號橫越山陰海岸直達米子站。\n• 【皆生溫泉・海濱夜宿】：米子站搭公車 15 分進駐皆生溫泉，眺望日本海白沙日落，享用海鮮會席與高濃度海濱鹽湯。",
    "spotIds": [
      "tottori",
      "kaike_onsen"
    ]
  },
  {
    "dayNumber": 4,
    "title": "Day 4：出雲雙雄與神話美肌名湯",
    "date": "2027-01-16",
    "baseStation": "米子駅 / 安來駅 / 松江駅 / 出雲市駅",
    "lodging": "玉造溫泉 和風旅館 (松江市)",
    "notes": "• 【月山富田城・戰國五大山城 (建議預留 2~2.5h)】：清晨自米子搭 JR 山陰本線至安來站，轉搭安來市營黃色巴士攻登戰國名城月山富田城，巡禮山中御殿與本丸天險。\n• 【松江城・國寶天守 (基本預留 1h)】：午後搭特急八雲號至松江站，登上國寶現存五天守之一的松江城千鳥破風。\n• 【出雲大社・日本神話之巔 (建議預留 1.5h)】：搭乘一畑電車沿宍道湖北岸至出雲大社前站，朝拜神樂殿 5.2 噸巨型注連繩與國寶本殿，祈求良緣。\n• 【玉作湯神社・願之石御守 (停留 40分)】：傍晚抵達玉造溫泉街最深處，參拜溫泉守護神，觸摸靈驗「願之石」並求取「葉之石」製作專屬奇蹟御守。\n• 【玉造溫泉・美肌神湯夜宿】：入住玉造溫泉街和風旅館，享受《出雲國風土記》記載「一濯則形容端正，兩洗則百病皆除」的千年神湯與豐盛會席料理。",
    "spotIds": [
      "gassan_toda",
      "matsue",
      "izumo_taisha",
      "tamatsukuri_yu_jinja",
      "tamatsukuri_onsen"
    ]
  },
  {
    "dayNumber": 5,
    "title": "Day 5：山陰小京都與長州維新城下町",
    "date": "2027-01-17",
    "baseStation": "松江駅 / 津和野駅 / 東萩駅",
    "lodging": "萩溫泉鄉 / 新山口飯店",
    "notes": "• 【津和野城・纜車加登山 (建議預留 1.5h)】：晨間搭特急超級隱岐號南下津和野，搭乘觀光登山纜車後再步行 15 分石垣稜線攻登津和野城跡，順遊殿町通錦鯉老街。\n• 【萩城・指月公園 (基本預留 1h)】：午後搭防長巴士前往萩城跡（指月公園平坦寬闊，漫步輕鬆），漫步世界遺產萩城下町菊濱海岸。\n• 【夜宿安排】：今晚夜宿萩溫泉鄉旅館或轉往新山口站前商務飯店。",
    "spotIds": [
      "tsuwano",
      "hagi"
    ]
  },
  {
    "dayNumber": 6,
    "title": "Day 6：周防岩國錦帶橋與廣島和平鯉城",
    "date": "2027-01-18",
    "baseStation": "新山口駅 / 廣島駅",
    "lodging": "廣島市區飯店 (八丁堀 / 廣島站前)",
    "notes": "• 【岩國城・空中纜車 (基本預留 1h)】：晨間前往岩國漫步錦帶橋，搭空中纜車登頂岩國城俯瞰錦川與瀨戶內海（天守出站平路 5 分，輕鬆好走）。\n• 【廣島城・市區平城 (基本預留 1h)】：午後前往廣島城（平地天守參觀武士文化）。\n• 【寶可夢中心 廣島 (SOGO 6F，預留 1h)】：廣島城往南步行 8 分鐘直達そごう廣島店本館 6F「寶可夢中心廣島」（全中國地區唯一官方旗艦直營店！），朝聖鎮店巨型『紅色暴鯉龍』雕像與廣島限定紅色暴鯉龍皮卡丘！\n• 【廣島和平紀念資料館 & 原爆圓頂 (預留 1.5h)】：自 SOGO 往南步行 5 分鐘進入和平紀念公園，參觀世界遺產原爆圓頂與「廣島和平紀念資料館」（丹下健三設計、米其林三星評鑑，門票 200 円，莊嚴震撼）。\n• 【和牛晚餐首選 (廣島和牛)】：晚餐強烈推薦二選一：\n  1. 鉄板焼「愛宕」(和平公園旁步行 5 分鐘，參觀完直接入座享用特選廣島牛/比婆牛)\n  2. 鉄板焼「神石」(廣島站直結 Granvia 頂樓 21F，坐擁市區高空百萬夜景，住站前首選)。\n• 【住宿】：廣島市區飯店 (八丁堀 / 廣島站前)。",
    "spotIds": [
      "iwakuni",
      "hiroshima",
      "pokemon_center_hiroshima",
      "hiroshima_peace_museum"
    ]
  },
  {
    "dayNumber": 7,
    "title": "Day 7：毛利元就大本營與波妞古港海景溫泉",
    "date": "2027-01-19",
    "baseStation": "廣島巴士中心 / 福山駅",
    "lodging": "鞆之浦溫泉 海景旅館 (福山市)",
    "notes": "• 【吉田郡山城・全山要塞 (建議預留 2h)】：由廣島巴士中心搭客運直達安藝高田，登山健行探訪毛利元就墓所與廣大郡山城山頂本丸。\n• 【福山城・鐵板張天守 (基本預留 1h)】：午後搭新幹線至福山站，北口直達福山城（新裝修鐵板張天守，0距離平坦好走）。\n• 【鞆之浦溫泉・波妞舞台夜宿】：福山站搭巴士 30 分抵達宮崎駿《崖上的波妞》舞台「鞆之浦溫泉」，入住海景溫泉旅館對望仙醉島。",
    "spotIds": [
      "yoshida_koriyama",
      "fukuyama",
      "tomonoura_onsen"
    ]
  },
  {
    "dayNumber": 8,
    "title": "Day 8：天空之城備中松山城 ➔ 岡山機場返台 (虎航 IT215)",
    "date": "2027-01-20",
    "baseStation": "福山駅 / 備中高梁駅 / 岡山機場",
    "lodging": "溫暖的家 (搭乘台灣虎航 IT215 返程)",
    "notes": "• 【備中松山城・天空之城 (建議預留 1.5h)】：清晨 07:30 由鞆之浦搭巴士至福山，搭山陽新幹線轉特急八雲號於 09:05 抵備中高梁站。09:20 搭預約乘合計程車至鞴峠，登山探訪現存唯一山城天守與貓城主三十郎。\n• 【特急八雲號直達岡山】：11:15 搭乘合計程車返回備中高梁站，搭乘 11:42 特急やくも 12號 (全車指定席，車程 34 分)，於 12:18 抵達岡山站。可在站內外帶岡山便當或特色伴手禮。\n• 【台灣虎航 IT215 返台班機 (提早 2.5~3 小時到機場)】：\n  - 航班資訊：台灣虎航 IT215 (岡山 OKJ ➔ 台北桃園 TPE)，15:55 準時起飛 (13:25 開櫃報到、15:10 關櫃)。\n  - 機場利木津巴士：岡山站西口 2 號乘車處搭乘 12:40 發車之利木津直達巴士 (車程 30 分，單程 780 円)。\n  - 機場報到安檢：約 13:10 抵達岡山桃太郎機場，起飛前 2 小時 45 分鐘充裕抵達！悠閒完成行李托運、安檢出境與免稅店採買，滿載 12 座名城回憶平安返台！",
    "spotIds": [
      "bitchu_matsuyama",
      "okayama_airport"
    ]
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { DEFAULT_SPOTS, DEFAULT_ITINERARY };
}
